FROM node:7

RUN mkdir -p /usr/www 
COPY . /usr/www
WORKDIR /usr/www

RUN npm install --production --silent
RUN npm run build --production --silent

CMD ["npm", "run", "start"]

# docker build -f Dockerfile.web -t localhost:5000/xbo-web . ; \
# 	docker build -f Dockerfile.server -t localhost:5000/xbo-server . ; \
# 	docker push localhost:5000/xbo-web; \
# 	docker push localhost:5000/xbo-server;

