version: '2.4'

volumes:
  mongo-xbo:

services:
  mongo:
    image: mongo:3.6.11
    container_name: mongo-xbo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-xbo:/data/db
  # xbo-web:
  #   image: localhost:5000/xbo-web:local
  #   build:
  #     context: .
  #     dockerfile: ./packages/client/Dockerfile
  #   command: yarn start
  #   container_name: xbo-web-dev
  #   restart: always
  #   volumes:
  #     - ./packages/client/src:/code/src
  #   environment:
  #     - REACT_APP_API_URL=http://localhost:9000
  #     - REACT_APP_PUSHBULLET_APP_CLIENT_ID=2TXDmPJN0tukzOqu19qvwNCju16SyMb7
  #   ports:
  #     - 3000:3000
  # server:
  #   image: localhost:5000/xbo-server:local
  #   build:
  #     context: .
  #     dockerfile: ./packages/server/Dockerfile
  #   command: yarn start # npm run start:dev
  #   container_name: xbo-server
  #   restart: always
  #   volumes:
  #     - ./packages/server/src:/code/src
  #   ports:
  #     - 9000:9000
  #   environment:
  #     - DB_HOST=mongo
  #     - DB_USER=
  #     - DB_PASSWORD=
  #     - PUSHBULLET_APP_CLIENT_ID=2TXDmPJN0tukzOqu19qvwNCju16SyMb7
  #     - PUSHBULLET_APP_CLIENT_SECRET=IlQ1SBBY9fRnWLRVEFSQMxkB5UIS9Rxt
