version: '2.4'

volumes:
  mongo-xbo:

services:
  mongo:
    image: mongo:4.2.13
    container_name: mongo-xbo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-xbo:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secure-admin-password
  client:
    image: localhost:5000/xbo-client:local
    build:
      context: .
      dockerfile: ./packages/client/Dockerfile
    command: yarn start
    stdin_open: true
    container_name: xbo-client-dev
    restart: always
    volumes:
      - ./packages/client/src:/client/src
    environment:
      - REACT_APP_API_URL=http://localhost:9000
      - REACT_APP_PUSHBULLET_APP_CLIENT_ID=
    ports:
      - 3000:3000
  server:
    image: localhost:5000/xbo-server:local
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    command: yarn start # yarn run start:dev
    container_name: xbo-server
    restart: always
    volumes:
      - ./packages/server/src:/server/src
    ports:
      - 9000:9000
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=xbo_dev
      - DB_USER=xbo_user
      - DB_PASSWORD=secure-xbo-password
      - PUSHBULLET_APP_CLIENT_ID=
      - PUSHBULLET_APP_CLIENT_SECRET=
